---
codecov:
  # This allows codecov to wait on all taskcluster checks to finish
  # it must be told which targetUrl to look out for. I figure we will
  # get the current tools.tc.net and whatever future rootUrl we end up
  # with should go in here before we move.
  ci:
    - tools.taskcluster.net

comment: off

coverage:
  precision: 0
  status:
    patch: off
    project:
      default:
        threshold: 1 # This combined with precision 0 should stop us from failing checks randomly

parsers:
  javascript:
    enable_partials: yes
