apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ${projectName}-${lowercase(procName)}
  labels:
    app.kubernetes.io/name: ${projectName}
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: ${projectName}-${lowercase(procName)}
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  schedule: ${schedule}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: ${projectName}
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: ${projectName}-${lowercase(procName)}
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: ${projectName}
            app.kubernetes.io/instance: '{{ .Release.Name }}'
            app.kubernetes.io/component: ${projectName}-${lowercase(procName)}
            app.kubernetes.io/part-of: taskcluster
            app.kubernetes.io/managed-by: helm
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: {$eval: 'deadlineSeconds'}
          containers:
          - name: ${projectName}-${lowercase(procName)}
            image: '{{ .Values.dockerImage }}'
            imagePullPolicy: Always
            args: ['${serviceName}/${procName}']
            resources:
              requests:
                cpu: '{{ .Values.${configName}.procs.${configProcName}.cpu }}'
                memory: '{{ .Values.${configName}.procs.${configProcName}.memory }}'
            env:
              - name: TASKCLUSTER_ROOT_URL
                value: '{{ .Values.rootUrl }}'
              - name: NODE_ENV
                value: 'production'
            envFrom:
              - secretRef:
                  name: ${projectName}
