apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${projectName}-${lowercase(procName)}
  labels:
    app.kubernetes.io/name: ${projectName}
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: ${projectName}-${lowercase(procName)}
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ${projectName}
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/component: ${projectName}-${lowercase(procName)}
      app.kubernetes.io/part-of: taskcluster
      app.kubernetes.io/managed-by: helm
  replicas: REPLICA_CONFIG_STRING
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/${projectName}-secret.yaml") . | sha256sum }}'
      labels:
        app.kubernetes.io/name: ${projectName}
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: ${projectName}-${lowercase(procName)}
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: ${projectName}
      containers:
      - name: ${projectName}
        image: '{{ .Values.dockerImage }}'
        imagePullPolicy: Always
        args: ['${serviceName}/${procName}']
        resources:
          requests:
            cpu: '{{ .Values.${configName}.procs.${configProcName}.cpu }}'
            memory: '{{ .Values.${configName}.procs.${configProcName}.memory }}'
        env:
          $flatten:
            - $if: 'needsService'
              then:
                name: PORT
                value: '80'
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
            - name: NODE_ENV
              value: 'production'
        envFrom:
            - secretRef:
                name: ${projectName}
        ports:
        - $if: 'needsService'
          then:
            containerPort: 80
        readinessProbe:
          $if: 'needsService'
          then:
            httpGet:
              path: ${readinessPath}
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 3
