apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${projectName}
data:
  $merge:
    $map: {$eval: secrets}
    each(s):
      ${uppercase(s.key)}: '{{ if typeIs "<nil>" ${s.val} }}{{ else }}{{ ${s.val} | toJson | trimAll "\"" | b64enc }}{{ end }}'
