kind: Service
apiVersion: v1
metadata:
  name: ${projectName}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ${projectName}
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: ${projectName}-${lowercase(procName)}
    app.kubernetes.io/part-of: taskcluster
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
