---
defaults:
  app:
    exchangePrefix:              'v1/'
    cachePurgeTableName:         'CachePurges'
    cachePurgeExpirationDelay:   '- 1 hour'
    cacheTime:                   10

  monitoring:
    level: !env:optional LEVEL

  server:
    # Port to listen for requests on
    port:                           !env:number PORT

    # Environment 'development' or 'production'
    env:                            'development'

    # Force SSL not useful when runnning locally
    forceSSL:                       !env:bool FORCE_SSL

    # Trust a forwarding proxy
    trustProxy:                     !env:bool TRUST_PROXY

  azure:
    accountId:                !env AZURE_ACCOUNT_ID

  taskcluster:
    rootUrl:                     !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId:                   !env TASKCLUSTER_CLIENT_ID
      accessToken:                !env TASKCLUSTER_ACCESS_TOKEN

  # AWS SDK configuration for publication of schemas and references
  aws:
    accessKeyId:      !env:optional AWS_ACCESS_KEY_ID
    secretAccessKey:  !env:optional AWS_SECRET_ACCESS_KEY
    # Default AWS region this is where the S3 bucket lives
    region:                         'us-west-2'
    # Lock API version to use the latest API from 2013 this is fuzzy locking
    # but it does the trick...
    apiVersion:                     '2014-01-01'

production:
  server:
    env:                          'production'

test:
  app:
    cachePurgeExpirationDelay:   '7 days'

  azure:
    accountId:                    'jungle'

  server:
    port:                         60415
    forceSSL:                     false
    trustProxy:                   true

verify:
  taskcluster:
    credentials:
      clientId:                   !env TASKCLUSTER_CLIENT_ID
      accessToken:                !env TASKCLUSTER_ACCESS_TOKEN
