kind: Service
apiVersion: v1
metadata:
  name: taskcluster-queue
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: taskcluster-queue
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-queue-web
    app.kubernetes.io/part-of: taskcluster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
