apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-built-in-workers-server
  labels:
    app.kubernetes.io/name: taskcluster-built-in-workers
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-built-in-workers-server
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: taskcluster-built-in-workers
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/component: taskcluster-built-in-workers-server
      app.kubernetes.io/part-of: taskcluster
      app.kubernetes.io/managed-by: helm
  replicas: {{ int (.Values.built_in_workers.procs.server.replicas) }}
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-built-in-workers-secret.yaml") . | sha256sum }}'
      labels:
        app.kubernetes.io/name: taskcluster-built-in-workers
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: taskcluster-built-in-workers-server
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: taskcluster-built-in-workers
      containers:
        - name: taskcluster-built-in-workers
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - built-in-workers/server
          resources:
            requests:
              cpu: '{{ .Values.built_in_workers.procs.server.cpu }}'
              memory: '{{ .Values.built_in_workers.procs.server.memory }}'
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
            - name: NODE_ENV
              value: production
          envFrom:
            - secretRef:
                name: taskcluster-built-in-workers
          ports: []
