apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: taskcluster-worker-manager-expire-workers
  labels:
    app.kubernetes.io/name: taskcluster-worker-manager
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-worker-manager-expire-workers
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  schedule: 0 0 * * *
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: taskcluster-worker-manager
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: taskcluster-worker-manager-expire-workers
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: taskcluster-worker-manager
            app.kubernetes.io/instance: '{{ .Release.Name }}'
            app.kubernetes.io/component: taskcluster-worker-manager-expire-workers
            app.kubernetes.io/part-of: taskcluster
            app.kubernetes.io/managed-by: helm
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: 86400
          containers:
            - name: taskcluster-worker-manager-expire-workers
              image: '{{ .Values.dockerImage }}'
              imagePullPolicy: Always
              args:
                - worker-manager/expire-workers
              resources:
                requests:
                  cpu: '{{ .Values.worker_manager.procs.expire_workers.cpu }}'
                  memory: '{{ .Values.worker_manager.procs.expire_workers.memory }}'
              env:
                - name: TASKCLUSTER_ROOT_URL
                  value: '{{ .Values.rootUrl }}'
                - name: NODE_ENV
                  value: production
              envFrom:
                - secretRef:
                    name: taskcluster-worker-manager
