apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-notify-handler
  labels:
    app.kubernetes.io/name: taskcluster-notify
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-notify-handler
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: taskcluster-notify
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/component: taskcluster-notify-handler
      app.kubernetes.io/part-of: taskcluster
      app.kubernetes.io/managed-by: helm
  replicas: {{ int (.Values.notify.procs.handler.replicas) }}
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-notify-secret.yaml") . | sha256sum }}'
      labels:
        app.kubernetes.io/name: taskcluster-notify
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: taskcluster-notify-handler
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: taskcluster-notify
      containers:
        - name: taskcluster-notify
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - notify/handler
          resources:
            requests:
              cpu: '{{ .Values.notify.procs.handler.cpu }}'
              memory: '{{ .Values.notify.procs.handler.memory }}'
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
            - name: NODE_ENV
              value: production
          envFrom:
            - secretRef:
                name: taskcluster-notify
          ports: []
