apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: taskcluster-queue-expiretaskgroups
  labels:
    app.kubernetes.io/name: taskcluster-queue
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-queue-expiretaskgroups
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  schedule: 0 0 * * *
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: taskcluster-queue
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: taskcluster-queue-expiretaskgroups
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: taskcluster-queue
            app.kubernetes.io/instance: '{{ .Release.Name }}'
            app.kubernetes.io/component: taskcluster-queue-expiretaskgroups
            app.kubernetes.io/part-of: taskcluster
            app.kubernetes.io/managed-by: helm
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: 86400
          containers:
            - name: taskcluster-queue-expiretaskgroups
              image: '{{ .Values.dockerImage }}'
              imagePullPolicy: Always
              args:
                - queue/expireTaskGroups
              resources:
                requests:
                  cpu: '{{ .Values.queue.procs.expireTaskGroups.cpu }}'
                  memory: '{{ .Values.queue.procs.expireTaskGroups.memory }}'
              env:
                - name: TASKCLUSTER_ROOT_URL
                  value: '{{ .Values.rootUrl }}'
                - name: NODE_ENV
                  value: production
              envFrom:
                - secretRef:
                    name: taskcluster-queue
