apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-secrets
data:
  TASKCLUSTER_ROOT_URL: '{{ if typeIs "<nil>" .Values.rootUrl }}{{ else }}{{ .Values.rootUrl | toJson | trimAll "\"" | b64enc }}{{ end }}'
  TASKCLUSTER_CLIENT_ID: '{{ if typeIs "<nil>" .Values.secrets.taskcluster_client_id }}{{ else }}{{ .Values.secrets.taskcluster_client_id | toJson | trimAll "\"" | b64enc }}{{ end }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ if typeIs "<nil>" .Values.secrets.taskcluster_access_token }}{{ else }}{{ .Values.secrets.taskcluster_access_token | toJson | trimAll "\"" | b64enc }}{{ end }}'
  AZURE_ACCOUNT_ID: '{{ if typeIs "<nil>" .Values.azureAccountId }}{{ else }}{{ .Values.azureAccountId | toJson | trimAll "\"" | b64enc }}{{ end }}'
  AZURE_TABLE_NAME: '{{ if typeIs "<nil>" .Values.secrets.azure_table_name }}{{ else }}{{ .Values.secrets.azure_table_name | toJson | trimAll "\"" | b64enc }}{{ end }}'
  AZURE_CRYPTO_KEY: '{{ if typeIs "<nil>" .Values.secrets.azure_crypto_key }}{{ else }}{{ .Values.secrets.azure_crypto_key | toJson | trimAll "\"" | b64enc }}{{ end }}'
  AZURE_SIGNING_KEY: '{{ if typeIs "<nil>" .Values.secrets.azure_signing_key }}{{ else }}{{ .Values.secrets.azure_signing_key | toJson | trimAll "\"" | b64enc }}{{ end }}'
  LEVEL: '{{ if typeIs "<nil>" .Values.secrets.level }}{{ else }}{{ .Values.secrets.level | toJson | trimAll "\"" | b64enc }}{{ end }}'
  FORCE_SSL: '{{ if typeIs "<nil>" .Values.forceSSL }}{{ else }}{{ .Values.forceSSL | toJson | trimAll "\"" | b64enc }}{{ end }}'
  AWS_ACCESS_KEY_ID: '{{ if typeIs "<nil>" .Values.secrets.aws_access_key_id }}{{ else }}{{ .Values.secrets.aws_access_key_id | toJson | trimAll "\"" | b64enc }}{{ end }}'
  AWS_SECRET_ACCESS_KEY: '{{ if typeIs "<nil>" .Values.secrets.aws_secret_access_key }}{{ else }}{{ .Values.secrets.aws_secret_access_key | toJson | trimAll "\"" | b64enc }}{{ end }}'
