apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: taskcluster-web-server-scanner
  labels:
    app.kubernetes.io/name: taskcluster-web-server
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-web-server-scanner
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  schedule: 0 0 * * *
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: taskcluster-web-server
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: taskcluster-web-server-scanner
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: taskcluster-web-server
            app.kubernetes.io/instance: '{{ .Release.Name }}'
            app.kubernetes.io/component: taskcluster-web-server-scanner
            app.kubernetes.io/part-of: taskcluster
            app.kubernetes.io/managed-by: helm
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: 86400
          containers:
            - name: taskcluster-web-server-scanner
              image: '{{ .Values.dockerImage }}'
              imagePullPolicy: Always
              args:
                - web-server/scanner
              resources:
                requests:
                  cpu: '{{ .Values.web_server.procs.scanner.cpu }}'
                  memory: '{{ .Values.web_server.procs.scanner.memory }}'
              env:
                - name: TASKCLUSTER_ROOT_URL
                  value: '{{ .Values.rootUrl }}'
                - name: NODE_ENV
                  value: production
              envFrom:
                - secretRef:
                    name: taskcluster-web-server
