apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-built-in-workers
data:
  TASKCLUSTER_ROOT_URL: '{{ if typeIs "<nil>" .Values.rootUrl }}{{ else }}{{ .Values.rootUrl | toJson | trimAll "\"" | b64enc }}{{ end }}'
  TASKCLUSTER_CLIENT_ID: '{{ if typeIs "<nil>" .Values.built_in_workers.taskcluster_client_id }}{{ else }}{{ .Values.built_in_workers.taskcluster_client_id | toJson | trimAll "\"" | b64enc }}{{ end }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ if typeIs "<nil>" .Values.built_in_workers.taskcluster_access_token }}{{ else }}{{ .Values.built_in_workers.taskcluster_access_token | toJson | trimAll "\"" | b64enc }}{{ end }}'
  LEVEL: '{{ if typeIs "<nil>" .Values.built_in_workers.level }}{{ else }}{{ .Values.built_in_workers.level | toJson | trimAll "\"" | b64enc }}{{ end }}'
