apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-ui
data:
  APPLICATION_NAME: '{{ if typeIs "<nil>" .Values.ui.application_name }}{{ else }}{{ .Values.ui.application_name | toJson | trimAll "\"" | b64enc }}{{ end }}'
  GRAPHQL_SUBSCRIPTION_ENDPOINT: '{{ if typeIs "<nil>" .Values.ui.graphql_subscription_endpoint }}{{ else }}{{ .Values.ui.graphql_subscription_endpoint | toJson | trimAll "\"" | b64enc }}{{ end }}'
  GRAPHQL_ENDPOINT: '{{ if typeIs "<nil>" .Values.ui.graphql_endpoint }}{{ else }}{{ .Values.ui.graphql_endpoint | toJson | trimAll "\"" | b64enc }}{{ end }}'
