apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-index
data:
  AZURE_ACCOUNT_ID: '{{ if typeIs "<nil>" .Values.azureAccountId }}{{ else }}{{ .Values.azureAccountId | toJson | trimAll "\"" | b64enc }}{{ end }}'
  LEVEL: '{{ if typeIs "<nil>" .Values.index.level }}{{ else }}{{ .Values.index.level | toJson | trimAll "\"" | b64enc }}{{ end }}'
  TASKCLUSTER_ROOT_URL: '{{ if typeIs "<nil>" .Values.rootUrl }}{{ else }}{{ .Values.rootUrl | toJson | trimAll "\"" | b64enc }}{{ end }}'
  TASKCLUSTER_CLIENT_ID: '{{ if typeIs "<nil>" .Values.index.taskcluster_client_id }}{{ else }}{{ .Values.index.taskcluster_client_id | toJson | trimAll "\"" | b64enc }}{{ end }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ if typeIs "<nil>" .Values.index.taskcluster_access_token }}{{ else }}{{ .Values.index.taskcluster_access_token | toJson | trimAll "\"" | b64enc }}{{ end }}'
  PULSE_HOSTNAME: '{{ if typeIs "<nil>" .Values.pulseHostname }}{{ else }}{{ .Values.pulseHostname | toJson | trimAll "\"" | b64enc }}{{ end }}'
  PULSE_USERNAME: '{{ if typeIs "<nil>" .Values.index.pulse_username }}{{ else }}{{ .Values.index.pulse_username | toJson | trimAll "\"" | b64enc }}{{ end }}'
  PULSE_PASSWORD: '{{ if typeIs "<nil>" .Values.index.pulse_password }}{{ else }}{{ .Values.index.pulse_password | toJson | trimAll "\"" | b64enc }}{{ end }}'
  PULSE_VHOST: '{{ if typeIs "<nil>" .Values.pulseVhost }}{{ else }}{{ .Values.pulseVhost | toJson | trimAll "\"" | b64enc }}{{ end }}'
  PULSE_NAMESPACE: '{{ if typeIs "<nil>" .Values.index.pulse_namespace }}{{ else }}{{ .Values.index.pulse_namespace | toJson | trimAll "\"" | b64enc }}{{ end }}'
  AWS_ACCESS_KEY_ID: '{{ if typeIs "<nil>" .Values.index.aws_access_key_id }}{{ else }}{{ .Values.index.aws_access_key_id | toJson | trimAll "\"" | b64enc }}{{ end }}'
  AWS_SECRET_ACCESS_KEY: '{{ if typeIs "<nil>" .Values.index.aws_secret_access_key }}{{ else }}{{ .Values.index.aws_secret_access_key | toJson | trimAll "\"" | b64enc }}{{ end }}'
  FORCE_SSL: '{{ if typeIs "<nil>" .Values.forceSSL }}{{ else }}{{ .Values.forceSSL | toJson | trimAll "\"" | b64enc }}{{ end }}'
  TRUST_PROXY: '{{ if typeIs "<nil>" .Values.trustProxy }}{{ else }}{{ .Values.trustProxy | toJson | trimAll "\"" | b64enc }}{{ end }}'
